<script setup lang="ts">
const { t, formatLocale } = useAppLocale()
const props = withDefaults(defineProps<{ item: any; checked?: boolean; selectable?: boolean; disabled?: boolean; checkboxLabel?: string; cover?: string; state?: string; detail?: string; progress?: number }>(), { selectable: true })
const emit = defineEmits<{ select: [checked: boolean] }>()
const position = ref<Record<string,string>>({}), tooltipOpen = ref(false)
const bytes = (n: number) => `${(n / (n >= 1073741824 ? 1073741824 : 1048576)).toLocaleString(formatLocale.value,{maximumFractionDigits:2})} ${t(n >= 1073741824 ? 'ГБ' : 'МБ')}`
const typeClass = computed(() => ({ 'Игра':'game','Патч':'patch','Бэкпорт':'backport','DLC':'dlc' }[props.item.type as string] || 'game'))
function show(event: Event) { const r = (event.currentTarget as HTMLElement).getBoundingClientRect(); const width = Math.min(430, window.innerWidth-24), height = Math.min(430, window.innerHeight-24); position.value = { left:`${Math.max(12,Math.min(r.left,window.innerWidth-width-12))}px`, top:`${Math.max(12,Math.min(r.bottom+6,window.innerHeight-height-12))}px`,width:`${width}px`,maxHeight:`${height}px` }; tooltipOpen.value = true }
</script>
<template><div class="pf-package-row"><input v-if="selectable !== false" type="checkbox" :checked="checked" :disabled="disabled" :aria-label="checkboxLabel || t(`Выбрать ${item.title}`)" @change="emit('select',($event.target as HTMLInputElement).checked)"><span v-else class="pf-check-space" /><div class="pf-cover"><img v-if="cover || item.iconUrl || item.iconId || item.groupIconId" :src="cover || item.iconUrl || `/api/packages/${item.iconId || item.groupIconId}?asset=icon`" alt="" loading="lazy" decoding="async"><span v-else>{{ item.type === 'Игра' ? item.title.charAt(0) : item.type }}</span></div><div class="pf-package-name"><strong :title="item.fileName">{{ item.title }}</strong><slot name="subtitle" /><div v-if="progress !== undefined" class="pf-progress"><i :style="{ width:`${Math.max(0,Math.min(100,progress))}%` }" /></div></div><div class="pf-type-wrap"><button type="button" class="pf-type" :class="typeClass" :aria-label="t(`Сведения о PKG: ${item.title}`)" @mouseenter="show" @mouseleave="tooltipOpen=false" @focus="show" @blur="tooltipOpen=false" @click="show">{{ t(item.type) }}</button><Teleport to="body"><div v-if="tooltipOpen" class="pf-metadata" :style="position" role="tooltip"><strong>{{ t('Сведения о пакете') }}</strong><dl><dt>{{ t('Файл') }}</dt><dd>{{ item.fileName }}</dd><dt>{{ t('Игра') }}</dt><dd>{{ item.titleId }}</dd><dt>Content ID</dt><dd>{{ item.contentId || '—' }}</dd><template v-for="[key,label] in [['appVersion','Версия'],['masterVersion','Исходная версия'],['requiredFirmware','Прошивка PKG'],['sdkFirmware','Версия SDK'],['contentType','Категория'],['libraryRoot','Папка'],['packageDigest','Отпечаток PKG']]" :key="key"><template v-if="item[key]"><dt>{{ t(label!) }}</dt><dd>{{ item[key!] }}</dd></template></template><dt>{{ t('Тип PKG') }}</dt><dd>{{ t(item.type) }}</dd><dt>{{ t('Размер') }}</dt><dd>{{ bytes(item.size) }}</dd></dl></div></Teleport></div><span class="pf-size">{{ bytes(item.size) }}</span><span class="pf-state" :class="state || item.state" :title="detail || item.detail">{{ t(detail || item.detail || '') }}</span><div class="pf-package-actions"><slot name="actions" /></div></div></template>
<style scoped>
.pf-package-row{display:flex;align-items:center;flex-wrap:wrap;gap:9px;min-height:54px;padding:7px 12px 7px 24px;border-top:1px solid #25242a;background:#19191c}.pf-package-row:hover{background:#202025}.pf-package-row>input,.pf-check-space{flex:0 0 18px;width:18px}.pf-package-row input{accent-color:#9977d8}.pf-cover{flex:0 0 32px;width:32px;height:38px;border-radius:5px;overflow:hidden;display:grid;place-items:center;background:#35343c;font-size:8px;text-align:center}.pf-cover img{width:100%;height:100%;object-fit:cover}.pf-package-name{flex:1 1 190px;min-width:130px}.pf-package-name strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px}.pf-type-wrap{flex:0 0 70px;display:flex}.pf-type{width:70px;border:0;padding:4px 6px;border-radius:4px;text-align:center;font-size:9px;font-weight:800}.game{color:#c3b8ff;background:#7968c826}.patch{color:#e3bd77;background:#c6974d25}.backport{color:#70c8d5;background:#3ba5b522}.dlc{color:#9dcd99;background:#78ac7122}.pf-size{flex:0 0 64px;color:#b8b4c0;font:10px 'DM Mono',monospace}.pf-state{flex:1 1 120px;min-width:120px;color:#a09da6;font-size:9px;line-height:1.35}.pf-state.installed,.pf-state.delivered{color:#8dc98c}.pf-state.sending,.pf-state.receiving,.pf-state.waiting,.pf-state.installing,.pf-state.verifying{color:#c4b9ff}.pf-state.failed,.pf-state.unconfirmed{color:#e78a80}.pf-state.skipped{color:#e3bd77}.pf-progress{height:3px;margin-top:7px;background:#393542;border-radius:3px;overflow:hidden}.pf-progress i{display:block;height:100%;background:linear-gradient(90deg,#7e6ed4,#b8aafb)}.pf-package-actions{display:flex;flex-wrap:wrap;align-items:center;justify-content:flex-end;gap:6px;margin-left:auto}.pf-metadata{position:fixed;z-index:100;overflow:auto;background:#25242b;border:1px solid #57525f;border-radius:9px;padding:14px;box-shadow:0 10px 30px #0008;font-size:11px;color:#e9e8ef;pointer-events:none}.pf-metadata dl{display:grid;grid-template-columns:110px minmax(0,1fr);gap:8px;margin-bottom:0}.pf-metadata dt{color:#a7a2b1}.pf-metadata dd{margin:0;overflow-wrap:anywhere;font-family:'DM Mono',monospace}
</style>
