<script setup lang="ts">
import type { PresetSummary } from '#shared/types/presets'
const { t } = useAppLocale()
const props=defineProps<{ preset?: { id:string;name:string;description?:string } }>()
const emit=defineEmits<{close:[];saved:[preset:PresetSummary]}>()
const name=ref(props.preset?.name || ''),description=ref(props.preset?.description || ''),busy=ref(false),message=ref(''),nameInput=ref<HTMLInputElement>()
async function save(){busy.value=true;try{const result=await $fetch<PresetSummary>('/api/presets',{method:'POST',body:{action:props.preset?'rename':'create',id:props.preset?.id,name:name.value,description:description.value}});emit('saved',result);emit('close')}catch(e:any){message.value=e?.data?.message || 'Не удалось сохранить пресет'}finally{busy.value=false}}
onMounted(()=>nameInput.value?.focus())
</script>
<template><Teleport to="body"><div class="preset-modal" @click.self="!busy && emit('close')" @keydown.esc="!busy && emit('close')"><form class="preset-dialog" role="dialog" aria-modal="true" :aria-label="t(preset?'Редактировать пресет':'Создать пресет')" @submit.prevent="save"><header><h2>{{ t(preset?'Редактировать пресет':'Создать пресет') }}</h2><button type="button" :disabled="busy" :aria-label="t('Закрыть')" @click="emit('close')">×</button></header><label>{{ t('Название пресета') }}<input ref="nameInput" v-model="name" maxlength="120" required :placeholder="t('Например, Гонки')"></label><label>{{ t('Описание') }}<textarea v-model="description" maxlength="2000" rows="4" :placeholder="t('Какие игры входят в эту подборку')" /></label><p v-if="message" role="alert">{{ t(message) }}</p><footer><button type="button" :disabled="busy" @click="emit('close')">{{ t('Отмена') }}</button><button class="primary" :disabled="busy || !name.trim()">{{ t(busy?'Сохраняем…':'Сохранить') }}</button></footer></form></div></Teleport></template>
<style scoped>.preset-modal{position:fixed;inset:0;z-index:45;display:grid;place-items:center;padding:24px;background:#050509bb}.preset-dialog{width:480px;max-width:100%;max-height:90vh;overflow:auto;background:#1e1d22;border:1px solid #4c4858;border-radius:16px;padding:24px;display:grid;gap:18px}header,footer{display:flex;justify-content:space-between;align-items:center;gap:10px}h2{margin:0;font-size:20px}label{display:grid;gap:8px;font-size:12px;color:#b8b4c0}input,textarea{width:100%;background:#151518;border:1px solid #4c4858;border-radius:8px;padding:10px;color:#eee;font:inherit}textarea{resize:vertical}button{border:1px solid #4c4858;border-radius:8px;padding:9px 14px;background:#28272d;color:#eee;cursor:pointer;font-size:12px}footer{justify-content:flex-end}p{font-size:12px;color:#e7a79f}</style>
