<script setup lang="ts">
import type { PresetSummary } from '#shared/types/presets'
const { t } = useAppLocale()
const props = defineProps<{ packageIds: string[] }>()
const emit = defineEmits<{ close: []; added: [] }>()
const items = ref<PresetSummary[]>([]), chosen = ref(''), createOpen = ref(false), message = ref(''), busy = ref(false), page = ref(1), pages = ref(1), q = ref('')
async function load() { try { const result = await $fetch<{ items: PresetSummary[]; pages: number; page: number }>('/api/presets', { query: { page: page.value, q: q.value } }); items.value = result.items; pages.value = result.pages; page.value = result.page } catch (e: any) { message.value = e?.data?.message || 'Не удалось загрузить пресеты' } }
async function created(preset: PresetSummary) { chosen.value = preset.id; q.value = preset.name; page.value = 1; await load() }
async function add() { busy.value = true; try { await $fetch('/api/presets', { method: 'POST', body: { action: 'add', id: chosen.value, packageIds: props.packageIds } }); emit('added'); emit('close') } catch (e: any) { message.value = e?.data?.message || 'Не удалось добавить в пресет' } finally { busy.value = false } }
onMounted(load)
</script>
<template>
  <div class="preset-overlay" @click.self="emit('close')"><section class="preset-picker" role="dialog" aria-modal="true" :aria-label="t('Добавить в пресет')"><header><h2>{{ t('Добавить в пресет') }}</h2><button @click="emit('close')" :aria-label="t('Закрыть')">×</button></header><p>{{ t('Выбрано файлов:') }} {{ packageIds.length }}</p><form @submit.prevent="page = 1; load()"><input v-model="q" :placeholder="t('Найти пресет')"><button>{{ t('Найти') }}</button></form><div class="preset-options"><label v-for="preset in items" :key="preset.id"><input v-model="chosen" type="radio" :value="preset.id" name="preset"><span><strong>{{ preset.name }}</strong><small>{{ t('Игр:') }} {{ preset.games }} · {{ t('Файлов:') }} {{ preset.files }} · {{ (preset.size / 1073741824).toFixed(2) }} {{ t('ГБ') }}</small></span></label><p v-if="!items.length">{{ t('Создайте свой первый пресет') }}</p></div><nav v-if="pages > 1"><button :disabled="page <= 1" @click="page--; load()">‹</button>{{ page }} / {{ pages }}<button :disabled="page >= pages" @click="page++; load()">›</button></nav><button @click="createOpen=true">{{ t('Создать пресет') }}</button><PresetEditor v-if="createOpen" @close="createOpen=false" @saved="created" /><p v-if="message" role="status">{{ t(message) }}</p><footer><button @click="emit('close')">{{ t('Отмена') }}</button><button :disabled="busy || !chosen || !packageIds.length" @click="add">{{ t('Добавить выбранное') }}</button></footer></section></div>
</template>
<style scoped>
.preset-overlay { position: fixed; inset: 0; z-index: 30; background: #07060bba; display: grid; place-items: center; padding: 25px; }.preset-picker { width: 560px; max-width: 100%; max-height: 90vh; overflow: auto; border: 1px solid #655077; border-radius: 18px; padding: 22px; background: #211b2c; color: #eee6fa; }header,footer,form,nav { display: flex; align-items: center; gap: 10px; }header { justify-content: space-between; }h2 { font-size: 20px; margin: 0; }p { color: #b2a2c5; font-size: 12px; }input:not([type]) { min-width: 0; flex: 1; border: 1px solid #584768; border-radius: 8px; background: #16111d; color: #eee6fa; padding: 10px; }button { border: 1px solid #645178; border-radius: 8px; padding: 9px 12px; background: #493260; color: inherit; font-size: 12px; }button:disabled { opacity: .4; }input { accent-color: #a986e3; }.preset-options { margin: 15px 0; max-height: 35vh; overflow: auto; }.preset-options label { display: flex; gap: 12px; padding: 12px; border-bottom: 1px solid #3e304d; cursor: pointer; }.preset-options small { display: block; margin-top: 4px; color: #b3a0c6; font-size: 11px; }nav { justify-content: center; margin: 10px; font-size: 12px; }footer { justify-content: flex-end; margin-top: 18px; }
</style>
