<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PackageFlow</AssemblyName>
    <Version>1.10.7</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>packageflow.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PackageFlow.Windows.Tests" />
    <EmbeddedResource Include="Assets/*.png" LogicalName="PackageFlow.Assets.%(Filename)%(Extension)" />
    <ProjectReference Include="../PackageFlow.Core/PackageFlow.Core.csproj" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
</Project>
